#version 460 core

layout (local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

struct DrawElementsCmd
{
    uint count;
    uint instance_count;
    uint first_index;
    uint base_vertex;
    uint base_instance;
};

struct AABB
{
    vec4 aabb_min;
    vec4 aabb_max;
};


layout (binding = 2, std430) restrict readonly buffer boundsbuffer
{
    AABB[] aabbs;
};

uniform int non_cull_amount = 1;
uniform mat4 projection_view;

layout (binding = 4, std430) restrict readonly buffer model_mat_buffer
{
    mat4[] model_matrices;
};

layout (binding = 6, std430) buffer draw_cmds_buffer
{
    DrawElementsCmd draw_cmds[];
};

AABB transform_AABB(AABB local, mat4 model)
{
    vec3 center = (local.aabb_max.xyz + local.aabb_min.xyz) * 0.5;
    vec3 extents = (local.aabb_max.xyz - local.aabb_min.xyz) * 0.5;

    vec3 world_center = vec3(model * vec4(center, 1.0));
    vec3 world_extents = abs(extents.x * model[0].xyz) +
    abs(extents.y * model[1].xyz) +
    abs(extents.z * model[2].xyz);

    vec3 world_min = world_center - world_extents;
    vec3 world_max = world_center + world_extents;
    return AABB(vec4(world_min, 1.0), vec4(world_max, 1.0));
}

bool is_aabb_in_frustum(mat4 view_projection, AABB world)
{
    vec3 absExtents = (world.aabb_max.xyz - world.aabb_min.xyz) * 0.5;
    for (int i = 0; i < 6; i++)
    {
        vec3 plane_normal;
        float plane_offset;
        if (i == 0)
        { // Left plane
          plane_normal = vec3(view_projection[0][3] + view_projection[0][0],
          view_projection[1][3] + view_projection[1][0],
          view_projection[2][3] + view_projection[2][0]);
          plane_offset = view_projection[3][3] + view_projection[3][0];
        }
        else if (i == 1)
        { // Right plane
          plane_normal = vec3(view_projection[0][3] - view_projection[0][0],
          view_projection[1][3] - view_projection[1][0],
          view_projection[2][3] - view_projection[2][0]);
          plane_offset = view_projection[3][3] - view_projection[3][0];
        }
        else if (i == 2)
        { // Bottom plane
          plane_normal = vec3(view_projection[0][3] + view_projection[0][1],
          view_projection[1][3] + view_projection[1][1],
          view_projection[2][3] + view_projection[2][1]);
          plane_offset = view_projection[3][3] + view_projection[3][1];
        }
        else if (i == 3)
        { // Top plane
          plane_normal = vec3(view_projection[0][3] - view_projection[0][1],
          view_projection[1][3] - view_projection[1][1],
          view_projection[2][3] - view_projection[2][1]);
          plane_offset = view_projection[3][3] - view_projection[3][1];
        }
        else if (i == 4)
        { // Near plane
          plane_normal = vec3(view_projection[0][3] + view_projection[0][2],
          view_projection[1][3] + view_projection[1][2],
          view_projection[2][3] + view_projection[2][2]);
          plane_offset = view_projection[3][3] + view_projection[3][2];
        }

        else if (i == 5)
        { // Far plane
          plane_normal = vec3(view_projection[0][3] - view_projection[0][2],
          view_projection[1][3] - view_projection[1][2],
          view_projection[2][3] - view_projection[2][2]);
          plane_offset = view_projection[3][3] - view_projection[3][2];
        }

        float length = length(plane_normal);
        plane_normal /= length;
        plane_offset /= length;
        vec3 center = (world.aabb_max.xyz + world.aabb_min.xyz) * 0.5f;
        float dist = dot(center, plane_normal) + plane_offset;
        float radius = dot(absExtents, abs(plane_normal));
        if (dist + radius < 0.0)
        {
            return false;
        }
    }
    return true;
}

void main()
{
    uint mesh_idx = gl_GlobalInvocationID.x;
    if(mesh_idx >= draw_cmds.length())
    {
        return;
    }

    draw_cmds[mesh_idx].instance_count = 0;
//    uint mesh_idx = gl_GlobalInvocationID.x;
//    AABB bounds = aabbs[mesh_idx];
//    mat4 model = model_matrices[mesh_idx];
//    bounds = transform_AABB(bounds, model);
//    draw_cmds[gl_GlobalInvocationID.x].instance_count =0;// is_aabb_in_frustum(projection_view, bounds) ? 1 : 0;
}