#version 460 core
layout (local_size_x = 32, local_size_y = 32, local_size_z = 1) in;
layout (binding = 0, rgba16f) uniform image2D output_image;
layout (binding = 1) uniform sampler2D bloom_texture;

uniform float time;


vec3 agxDefaultContrastApprox(vec3 x) {
    vec3 x2 = x * x;
    vec3 x4 = x2 * x2;

    return + 15.5 * x4 * x2
    - 40.14 * x4 * x
    + 31.96 * x4
    - 6.868 * x2 * x
    + 0.4298 * x2
    + 0.1191 * x
    - 0.00232;
}

vec3 agx(vec3 val)
{
    const mat3 agx_mat = mat3(
    0.842479062253094, 0.0423282422610123, 0.0423756549057051,
    0.0784335999999992, 0.878468636469772, 0.0784336,
    0.0792237451477643, 0.0791661274605434, 0.879142973793104);

    const float min_ev = -12.47393f;
    const float max_ev = 4.026069f;

    // Input transform
    val = agx_mat * val;

    // Log2 space encoding
    val = clamp(log2(val), min_ev, max_ev);
    val = (val - min_ev) / (max_ev - min_ev);

    // Apply sigmoid function approximation
    val = agxDefaultContrastApprox(val);

    return val;
}

vec3 agxEotf(vec3 val)
{
    const mat3 agx_mat_inv = mat3(
    1.19687900512017, -0.0528968517574562, -0.0529716355144438,
    -0.0980208811401368, 1.15190312990417, -0.0980434501171241,
    -0.0990297440797205, -0.0989611768448433, 1.15107367264116);

    // Undo input transform
    val = agx_mat_inv * val;

    // I enabled this line to do linear to srgb in line 180 for all tonemappings.
    // sRGB IEC 61966-2-1 2.2 Exponent Reference EOTF Display
    val = pow(val, vec3(2.2));

    return val;
}

vec3 agxLook(vec3 val)
{
    const vec3 lw = vec3(0.2126, 0.7152, 0.0722);
    float luma = dot(val, lw);

    // Default look
    vec3 offset = vec3(0.0);
    vec3 slope = vec3(1.0);
    vec3 power = vec3(1.0, 1.0, 1.0);
    float sat = 1.0;

    // ASC CDL
    val = pow(val * slope + offset, power);
    return luma + sat * (val - luma);
}

vec3 tonemapping_AgX(vec3 color)
{
    color = agx(color);
    color = agxLook(color);
    color = agxEotf(color);
    return color;
}

vec3 noise(vec2 uv, float time)
{
    mat2x3 uvs = mat2x3(uv.xxx, uv.yyy) + mat2x3(vec3(0.0, 0.1, 0.2), vec3(0.0, 0.3, 0.4));
    return fract(sin(uvs * vec2(12.98989, 78.233) * time) * 43856.4533);
}

// Input color is non-negative and resides in the Linear Rec. 709 color space.
// Output color is also Linear Rec. 709, but in the [0, 1] range.

vec3 PBRNeutralToneMapping( vec3 color ) {
    const float startCompression = 0.8 - 0.04;
    const float desaturation = 0.15;

    float x = min(color.r, min(color.g, color.b));
    float offset = x < 0.08 ? x - 6.25 * x * x : 0.04;
    color -= offset;

    float peak = max(color.r, max(color.g, color.b));
    if (peak < startCompression) return color;

    const float d = 1. - startCompression;
    float newPeak = 1. - d * d / (peak + d - startCompression);
    color *= newPeak / peak;

    float g = 1. - 1. / (desaturation * (peak - newPeak) + 1.);
    return mix(color, newPeak * vec3(1, 1, 1), g);
}

float rand(vec2 v)
{
    return fract(sin(dot(v, vec2(12.9898, 78.233))) * 43758.5453);
}

//https://www.shadertoy.com/view/lsdXRn
struct ColorGradingPreset
{
    vec3 gain;
    vec3 gamma;
    vec3 lift;
    vec3 presaturation;
    vec3 colorTemperatureStrength;
    float colorTemperature; // in K
    float colorTemperatureBrightnessNormalization;
};

vec3 colorTemperatureToRGB(const in float temperature)
{
    mat3 m = (temperature <= 6500.0) ? mat3(vec3(0.0, -2902.1955373783176, -8257.7997278925690),
    vec3(0.0, 1669.5803561666639, 2575.2827530017594),
    vec3(1.0, 1.3302673723350029, 1.8993753891711275)) :
    mat3(vec3(1745.0425298314172, 1216.6168361476490, -8257.7997278925690),
    vec3(-2666.3474220535695, -2173.1012343082230, 2575.2827530017594),
    vec3(0.55995389139931482, 0.70381203140554553, 1.8993753891711275));
    return clamp(vec3(m[0] / (vec3(clamp(temperature, 1000.0, 40000.0)) + m[1]) + m[2]), vec3(0.0), vec3(1.0));
}

vec3 colorGradingProcess(const in ColorGradingPreset p, in vec3 c)
{
    float originalBrightness = dot(c, vec3(0.2126, 0.7152, 0.0722));
    c = mix(c, c * colorTemperatureToRGB(p.colorTemperature), p.colorTemperatureStrength);
    float newBrightness = dot(c, vec3(0.2126, 0.7152, 0.0722));
    c *= mix(1.0, (newBrightness > 1e-6) ? (originalBrightness / newBrightness) : 1.0, p.colorTemperatureBrightnessNormalization);
    c = mix(vec3(dot(c, vec3(0.2126, 0.7152, 0.0722))), c, p.presaturation);
    return pow((p.gain * 2.0) * (c + (((p.lift * 2.0) - vec3(1.0)) * (vec3(1.0) - c))), vec3(0.5) / p.gamma);
}

ColorGradingPreset ColorGradingPreset1 = ColorGradingPreset(
vec3(0.5),   // Gain
vec3(0.5),   // Gamma
vec3(0.5),   // Lift
vec3(1.0),   // Presaturation
vec3(0.0),   // Color temperature strength
6500.0,      // Color temperature (in K)
0.0          // Color temperature brightness normalization factor
);

ColorGradingPreset ColorGradingPreset2 = ColorGradingPreset(
vec3(0.8),   // Gain
vec3(0.4),   // Gamma
vec3(0.5),   // Lift
vec3(1.0),   // Presaturation
vec3(1.0),   // Color temperature strength
3000.0,      // Color temperature (in K)
1.0          // Color temperature brightness normalization factor
);

ColorGradingPreset ColorGradingPreset3 = ColorGradingPreset(
vec3(0.51, 0.55, 0.53), // Gain
vec3(0.45, 0.57, 0.55), // Gamma
vec3(0.5,  0.4,  0.6),  // Lift
vec3(1.0,  0.9,  0.8),  // Presaturation
vec3(1.0,  1.0,  1.0),  // Color temperature strength
6500.0,                 // Color temperature (in K)
0.0                     // Color temperature brightness normalization factor
);


void main()
{
    ivec2 pixel_coord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 output_image_size = imageSize(output_image);
    vec2 uv = (vec2(pixel_coord) + 0.5) / vec2(output_image_size);
    if (pixel_coord.x >= output_image_size.x || pixel_coord.y >= output_image_size.y)
    {
        return;
    }
    vec4 pixel_color = imageLoad(output_image, pixel_coord);
    vec3 color = pixel_color.rgb;
    color += texture(bloom_texture, uv).rgb;
    color = mix(color, tonemapping_AgX(color), 1.0);
    color = mix(color, colorGradingProcess(ColorGradingPreset2, color), 1.0);
    color = color / (color + vec3(1.0));
    color = pow(color, vec3(1.0 / 2.2));

    vec2 coord = vec2(pixel_coord);
    vec2 outside = modf(uv * vec2(output_image_size), coord);
    vec3 noise00 = noise(pixel_coord / output_image_size, time);
    vec3 noise01 = noise((pixel_coord + vec2(0, 1)) / output_image_size, time);
    vec3 noise10 = noise((pixel_coord + vec2(1, 0)) / output_image_size, time);
    vec3 noise11 = noise((pixel_coord + vec2(1, 1)) / output_image_size, time);
    vec3 noise = mix(mix(noise00, noise01, outside.y),
                     mix(noise10, noise11, outside.y), outside.x) * vec3(0.7, 0.6, 0.8);
    float speed = 15.0f;
    float x = rand(uv + rand(vec2(int(time * speed), int(-time * speed))));
    float noise_fact = 0.035;
    color = color + (x * -noise_fact) + (noise_fact / 2);
    imageStore(output_image, pixel_coord, vec4(color, pixel_color.a));
}